// Code generated by mockery v2.45.1. DO NOT EDIT.

package internal

import mock "github.com/stretchr/testify/mock"

// MockredisClient is an autogenerated mock type for the redisClient type
type MockredisClient struct {
	mock.Mock
}

type MockredisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockredisClient) EXPECT() *MockredisClient_Expecter {
	return &MockredisClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockredisClient) Get(key string) (string, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockredisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockredisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockredisClient_Expecter) Get(key interface{}) *MockredisClient_Get_Call {
	return &MockredisClient_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockredisClient_Get_Call) Run(run func(key string)) *MockredisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockredisClient_Get_Call) Return(_a0 string, _a1 error) *MockredisClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockredisClient_Get_Call) RunAndReturn(run func(string) (string, error)) *MockredisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *MockredisClient) Set(key string, value string) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockredisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockredisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockredisClient_Expecter) Set(key interface{}, value interface{}) *MockredisClient_Set_Call {
	return &MockredisClient_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockredisClient_Set_Call) Run(run func(key string, value string)) *MockredisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockredisClient_Set_Call) Return(_a0 error) *MockredisClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockredisClient_Set_Call) RunAndReturn(run func(string, string) error) *MockredisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockredisClient creates a new instance of MockredisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockredisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockredisClient {
	mock := &MockredisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
